### ISSUE TITLE
Welcome Screen Log In Accepts any Input While Logged Into User / Potential Log Out Failure

### ISSUE THREAD

**Issue by parcelt** [JakeHam/TheVirtualCloset#26]
Summary: After logging in with a valid user and then logging out of that user to then be back on the initial welcome page, I am able to then login with credentials that are not from a valid user.

Severity: Critical and Blocker

Description: As mentioned above, after logging out of the application through the side menu option, when initially being logged in as a user, when back on the Welcome to your Virtual Closet! page, one is able to log in with any value (string, number, etc.) in both the email and password text-boxes after hitting "Submit". This includes having nothing in either of the email and password text-boxes as well. Maybe this is an issue with the application that it is still under the impression that it is logged in as the former user and that the log out functionality was not completed.

Example of text-box information that logs in to application after hitting "Submit":
![image](https://cloud.githubusercontent.com/assets/26122639/25458720/b0e0dc88-2aa0-11e7-8c55-c31ec7e13fbd.png)

**Comment by chensonghu2013** [comment]
Thinking that there is no any input validation, this problem also happens in the size of the item or in item. We can input anything as we like.

**Comment by JakeHam** [comment]
Fixed!
