### ISSUE TITLE
Options page is blank

### ISSUE THREAD

**Issue by AlecMoran** [JakeHam/TheVirtualCloset#39]
Summary: Options page is blank

Severity: Blocker

Description: The Options page is currently blank aside from a header text that reads "Options Blank Page" (these "Blank Page" headers appear throughout the app in almost every page, but I have refrained from reporting it since it doesn't technically interfere with any usability).  According to the provided Design and Planning document, this Options page should contain various buttons used to change the user's profile information and settings.  

![file_000 9](https://cloud.githubusercontent.com/assets/25870868/25516412/1b7ebfd2-2bb0-11e7-9ad8-18e14b7e10ac.png)

**Comment by JakeHam** [comment]
Fixed!
