### ISSUE TITLE
Login information shown, even after logout (Ionic view)

### ISSUE THREAD

**Issue by akoerwitz** [JakeHam/TheVirtualCloset#44]
Severity: Severe
Description: On top of the password always being visible on the login screen, when the logout action occurs the login information remains filled on the login screen. Setting the fields to an empty string on create of the login activity may fix this issue.
![img_0335 1](https://cloud.githubusercontent.com/assets/26191916/25550978/2958cfe6-2c44-11e7-97ff-4b1f88ccdcf3.PNG)

**Comment by ashishvinodkumar** [comment]
Fixed!
